### ISSUE TITLE
Crash at click open button

### ISSUE THREAD

**Issue by ALuoBo** [xiaozhuang799/AndFasterSerialPort#1]
使用拥有root 权限的模拟器，安装后点击打开按钮，第一次提示给予管理员权限，给予权限之后，anr
然后重新打开软件，点击打开按钮，应用崩溃

**Comment by ALuoBo** [comment]
![image](https://user-images.githubusercontent.com/45779049/169690331-d95ccce4-cc5c-4e58-93b7-25b6ddb9f237.png)
![image](https://user-images.githubusercontent.com/45779049/169690344-c63163db-0172-48ca-ad5f-d46bb7804b43.png)

**Comment by xiaozhuang799** [comment]
不要用电脑的虚拟机，请用带串口的真机测试



发自我的iPhone


------------------ Original ------------------
From: ALuoBo ***@***.***&gt;
Date: Sun,May 22,2022 6:11 PM
To: xiaozhuang799/AndFasterSerialPort ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [xiaozhuang799/AndFasterSerialPort] Crash at click open button(Issue #1)

**Comment by ALuoBo** [comment]
> 

好的，谢谢，可惜手头上没有。请教一下，串口通讯的话是不是要放在service 中去处理？

**Comment by xiaozhuang799** [comment]
是的呢，数据轮询放在service，与UI没交互的，可以通过rxjava进行UI刷新。



发自我的iPhone


------------------ Original ------------------
From: ALuoBo ***@***.***&gt;
Date: Sun,May 22,2022 6:16 PM
To: xiaozhuang799/AndFasterSerialPort ***@***.***&gt;
Cc: Jon ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [xiaozhuang799/AndFasterSerialPort] Crash at click open button(Issue #1)





   
好的，谢谢，可惜手头上没有。请教一下，串口通讯的话是不是要放在service 中去处理？
